title: Ilan Olkies

description: Blog about mobile developing and more stuff.

baseurl: ""
url: "https://ilanolkies.github.io"

twitter_username: ilanolkies
github_username:  ilanolkies
instagram_username: ilanolkies
linkedin_username: ilanolkies

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-octicons

sass:
    load_paths:
        - _sass
        - node_modules

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - /node-modules
  - package.json
  - tag_gen.py
  - yarn.lock